swagger: '2.0'
info:
  title: findsingleItem
  x-ibm-name: findsingleitem
  version: 1.0.0
  description: API to find info for a single item.  Uses getFindsingleItem Service
schemes:
  - https
basePath: /findSingleItem
produces:
  - application/json
consumes:
  - application/json
x-ibm-configuration:
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: true
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: GET
          target-url: >-
            http://cap-sg-prd-2.securegateway.appdomain.cloud:18835$(request.path)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: blocklist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
  properties:
    target-url:
      value: 'http://cap-sg-prd-2.securegateway.appdomain.cloud:18835/findSingleItem'
      description: The URL of the target service
      encoded: false
  catalogs: {}
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  getFindsingleItem_response_200:
    type: object
    properties:
      DFH0XCP1:
        type: object
        properties:
          returnCode:
            type: integer
            minimum: 0
            maximum: 99
          responseMsg:
            type: string
            maxLength: 79
          findSingleItem:
            type: object
            properties:
              itemInfo:
                type: object
                properties:
                  itemNum:
                    type: integer
                    minimum: 0
                    maximum: 9999
                  description:
                    type: string
                    maxLength: 40
                  dept:
                    type: integer
                    minimum: 0
                    maximum: 999
                  price:
                    type: string
                    maxLength: 6
                  inStockQty:
                    type: integer
                    minimum: 0
                    maximum: 9999
                  onOrderQty:
                    type: integer
                    minimum: 0
                    maximum: 999
paths:
  '/{itemNum}':
    get:
      tags:
        - findsingleItem
      operationId: getFindsingleItem
      parameters:
        - name: Authorization
          in: header
          required: false
          type: string
        - name: itemNum
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/getFindsingleItem_response_200'
